version: '2'
services:
  redislocal:
    image: redis:6.0.6
    hostname: localhost
    ports:
    - 6379:6379
    container_name: redis-local

  mysqllocal:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: localhost
    environment:
      MYSQL_ROOT_PASSWORD: redismon!@#
      MYSQL_USER: redismon
      MYSQL_PASSWORD: redismon!@#
      MYSQL_DATABASE: redismon
    ports:
    - 3306:3306
    container_name: mysql-local
    volumes:
      - ./data/mysql:/var/lib/mysql
